site_name: Desenvolvimento Aberto 2021/2
repo_url: https://github.com/insper/dev-aberto/
repo_name: Dev Aberto
site_url: https://insper.github.io/dev-aberto/

theme:
    name: 'material'

extra_css:
  - css/custom.css

nav:
  - 'Home': 'index.md'
  - 'burocracias.md'
  - 'Skills e avaliação': 'regras.md'
  - 'Alunos': 'alunos.md'
  - 'Aulas':
    - 'aulas/01-ciclo-de-vida-bug/index.md'
    - 'aulas/02-comunidades-de-software/index.md'
    - 'aulas/03-documentacao-de-software/index.md'
    - 'aulas/04-discussao-documentacao-de-software/index.md'
    - 'aulas/05-projeto-profissional/index.md'
    - 'aulas/06-distribuicao-software/index.md'
    - 'aulas/07-localizacao/index.md'
    - 'aulas/08-testes-automatizados/index.md'
    - 'aulas/09-licencas/index.md'
    - 'aulas/10-minha-primeira-contribuicao/index.md'
  - 'Impacto': 
    - '2021/2': 'impacto.md'
    - '2020/1': 'impacto-2020.md'
    - '2019/2': 'impacto-2019.md'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - js/markdown-enhancer.js

markdown_extensions:
  - attr_list
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: "docs/_snippets"
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins: 
  - git-revision-date-localized