site_name: Open Source Development 2024/2
repo_url: https://github.com/insper/open-dev/
repo_name: Open Dev
site_url: https://insper.github.io/open-dev/

theme:
    name: 'material'

extra_css:
  - css/custom.css
  - css/people.css

nav:
  - 'Home': 'index.md'
  - 'syllabus.md'
  - 'assessment.md'
  - 'students.md'
    # - 'Agenda apresentações': 'agenda_apresentacoes.md'
  - 'Lessons':
    - 'lessons/01-distributed-workflow/index.md'
    - 'lessons/02-software-and-communities/index.md'
    - 'lessons/02-xpresentations-communities/index.md'
    - 'lessons/03-software-documentation/index.md'
    - 'lessons/04-professional-project/index.md'
    - 'lessons/05-python-packaging/index.md'
#    - 'lessons/06-localization-translation/index.md'
#    - 'lessons/07-code-quality/index.md'
#    - 'lessons/08-automated-testing/index.md'
#    - 'lessons/09-releases/index.md'
#    - 'lessons/10-first-contribution/index.md'
#    - lessons/11-floss-people/index.md
#    - lessons/12-licenses/index.md
  - 'Impact': 
    - '2023/2': 'impact.md'
    - '2022/2': 'impact-2022.md'
    - '2021/2': 'impact-2021.md'
    - '2020/1': 'impact-2020.md'
    - '2019/2': 'impact-2019.md'
  - 'Ongoing projects':
    - 'projects/2024/2/index.md'

extra_javascript:
  - js/markdown-enhancer.js

markdown_extensions:
  - attr_list
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: "docs/_snippets"
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

