site_name: Desenvolvimento Aberto 2019/2
repo_url: https://github.com/insper/dev-aberto/

theme:
    name: 'material'
    logo: 
      icon: 'developer_mode'

nav:
  - 'Home': 'index.md'
  - 'Skills e avaliação': 'regras.md'
  - 'Alunos': 'alunos.md'
  - 'Impacto': 'impacto.md'

markdown_extensions:
  - pymdownx.snippets:
      base_path: "docs/_snippets"
      check_paths: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.tasklist
